/**
 * Shared effect-list machinery for items whose effects are DATA consumed by
 * the rules layer (bead yb6). Talents pioneered the shape; gear, weapons and
 * armour share it so pack entries can carry live mechanical effects without
 * per-type schema forks.
 *
 * Consumers:
 * - rules/funnel.ts: kinds "test-modifier"/"attack-modifier" feed test rolls.
 * - rules/talent-effects.ts: registered handler kinds ("wounds-max", ...).
 * - rules/adapter.ts damage pipeline: "damage-flat"/"critical-damage".
 *
 * Whether an owned item's effects are live is decided by
 * {@link effectsAreLive}: talents are always "known"; physical items must be
 * equipped (worn armour, carried gear/weapons). (Equip-state semantics
 * VERIFY-flagged per bead yb6 — e.g. consumed drugs will need a use flow.)
 */

export interface EffectData {
	kind?: string;
	testKey?: string | null;
	value?: number;
	/** Dice expression for effects the book prints as dice (e.g. "1d10+4"). */
	dice?: string;
	label?: string;
	/** Guard: only applies when the matching context flag is set. */
	condition?: string;
}

/** Schema factory for the effect list; identical shape across item types. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- matches Talent's inferred field type
export function effectsField() {
	return new foundry.data.fields.ArrayField(
		new foundry.data.fields.SchemaField({
			kind: new foundry.data.fields.StringField({
				initial: "test-modifier",
				required: true,
				nullable: false,
			}),
			testKey: new foundry.data.fields.StringField({
				initial: "",
			}),
			value: new foundry.data.fields.NumberField({
				integer: true,
				initial: 0,
			}),
			/** Dice expression (epic 0hap): used by dice-valued kinds like
			 * "corruption" where the book prints "1d10+4" rather than a flat
			 * number. Empty = fall back to `value`. */
			dice: new foundry.data.fields.StringField({
				initial: "",
			}),
			label: new foundry.data.fields.StringField({
				initial: "",
			}),
			condition: new foundry.data.fields.StringField({
				initial: "",
			}),
		}),
		{ initial: () => [] },
	);
}

const EQUIP_STATES_FOR_EFFECTS: Record<string, string[]> = {
	armour: ["worn"],
	gear: ["carried"],
	"melee-weapon": ["carried"],
	"ranged-weapon": ["carried"],
};

/**
 * Whether an owned item of `itemType` in `equipState` contributes its
 * effects. Talents are always live (known, not carried); physical item types
 * contribute when equipped. Unknown types never contribute (opt-in via the
 * table).
 */
export function effectsAreLive(
	itemType: string | undefined,
	equipState: string | undefined,
): boolean {
	// Known-item types (not carried): talents and psychic powers (bead sa6 —
	// power effects feed Focus Power Tests; book p157 "Modifier,
	// Characteristic Bonuses... generated by Psychic Techniques" interplay
	// is per-technique, but owned power effects are always "known").
	// Rulebook traits (bead 25ii) are likewise INNATE — no equip state, the
	// actor always has them; their effect rows feed the funnel (bead zyv1).
	if (
		itemType === "talent" ||
		itemType === "psychicpower" ||
		itemType === "trait"
	)
		return true;
	const states = itemType ? EQUIP_STATES_FOR_EFFECTS[itemType] : undefined;
	return states !== undefined && states.includes(equipState ?? "");
}

/**
 * Dice expressions contributed by "corruption" effect rows (epic 0hap): the
 * Summon Daemon power prints "1d10+4 Corruption Points" (EA p83). Pure: the
 * adapter rolls the expressions and adds the total to the actor. `dice` wins;
 * an integer `value` is used as a flat fallback.
 */
export function corruptionExpressions(
	effects: EffectData[] | undefined,
): string[] {
	const out: string[] = [];
	for (const effect of effects ?? []) {
		if (effect.kind !== "corruption") continue;
		const dice = (effect.dice ?? "").trim();
		if (dice) out.push(dice);
		else if (typeof effect.value === "number" && effect.value !== 0) {
			out.push(String(effect.value));
		}
	}
	return out;
}

/**
 * Blank effect row for the sheets' add-effect control; values mirror the
 * schema defaults (test-modifier, unkeyed, zero).
 */
export function blankEffect(): Required<EffectData> {
	return {
		kind: "test-modifier",
		testKey: "",
		value: 0,
		dice: "",
		label: "",
		condition: "",
	};
}

/** Effects list with a blank row appended (pure; sheet add-effect action). */
export function withAddedEffect(
	effects: EffectData[] | undefined,
): EffectData[] {
	return [...(effects ?? []), blankEffect()];
}

/** Effects list minus the row at `index` (pure; sheet remove control). */
export function withoutEffectAt(
	effects: EffectData[],
	index: number,
): EffectData[] {
	return effects.filter((_, i) => i !== index);
}